[General]
frontend=widgetsboxmodel
hotkey=Meta+P
notifiedUnsupportedHotkey=true
showTray=true
standsalone_note_shown=true
telemetry=false

[albert]
global_handler_enabled=true

[applications]
enabled=true
global_handler_enabled=true
terminal=Alacritty

[calculator_muparser]
enabled=true
global_handler_enabled=true

[calculator_qalculate]
enabled=true

[chromium]
enabled=false

[pluginregistry]
global_handler_enabled=false
trigger_handler_enabled=false

[python]
enabled=false

[qmlboxmodel]
alwaysOnTop=false
hideOnFocusLoss=false
showCentered=true
windowPosition=@Point(0 0)

[snippets]
enabled=true
global_handler_enabled=true

[system]
command_poweroff=poweroff
command_reboot=reboot
enabled=true
global_handler_enabled=true
reboot=systemctl reboot
shutdown=systemctl poweroff

[terminal]
enabled=true

[widgetsboxmodel]
action_item_padding=6
action_item_selection_border_radius=11
action_item_selection_border_width=0
alwaysOnTop=true
clearOnHide=true
clientShadow=true
darkTheme=Default Dark
disable_input_method=true
displayIcons=true
displayScrollbar=false
displayShadow=true
followCursor=true
hideOnClose=false
hideOnFocusLoss=true
historySearch=true
input_border_radius=11
input_font_size=18
input_padding=5
itemCount=5
lightTheme=Default Dark
quitOnClose=false
result_item_horizontal_spacing=6
result_item_icon_size=39
result_item_padding=6
result_item_selection_border_radius=11
result_item_selection_border_width=0
result_item_subtext_font_size=8
result_item_text_font_size=13
result_item_vertical_spacing=2
showCentered=true
showFallbacksOnEmpty=true
systemShadow=true
windowPosition=@Point(0 0)
window_border_radius=18
window_border_width=1
window_padding=7
window_shadow_offset=8
window_shadow_size=80
window_spacing=7
window_width=640
